sudo: required
language: go
go:
- 1.8
services:
- docker
after_success:
- source ./build/travis-utils.sh
- if is_travis_push_env; then docker login -u $DOCKER_USER -p $DOCKER_PASSWORD; fi
- if is_travis_push_env; then make push; fi
- if is_travis_release_env; then make push-latest; fi
env:
  global:
  - secure: GRu1oVskiKAPNFmejL/hDgySM/m7R9mBcvrC3sp/d8skPYvpS0Ypd8byy/evXMlv3oZEAaFaR2xUZ4O2xks9i2s3nnE41MIGcCLEAer6OvWb9fzkcL9/D36bAiA2y64qHj+sIJETwwJtm8YviQnlT39eRTwIXq8spF5Luo5HWiFo4HA/nnBaq/pwNuKtv5tzQViQsQ+WfVDjtxviydqxlvPTfcSiZw4wIXvTqapvzS4vkI/Mw1J2K7muEcmu2GF8MRd1MVtxmU2UZjE8MrG4YxeM6m9h9KC8n+Lfi5aPP2rzuWTcPEjU8Pz6Q9obgsn+NZUD59s2dkcqDZUkvZuvrAqaF6X4bB9FjBDBks65BNRnt1YUN+cxxDriYMbO5PuQ44P0sZ3aueiWDI/uDwFcGTXBPoWv+FRe0mzV69YZNH7LMbSFJ90sZgq2Ckwodz+Szk6eoD5iGUvOeNWv1yz2rLnxJgMYTdSDrimpa+R+3QV7BjBlBPJTqtIvWBOSrx50Tl48O9d6NWvc+VN9ZjlWJd5RghcAsQwxBGtHwpTxdcydtpG75RiNckCKwqzjeZDiv5bUQGgvQrzl6mwhB+18Hze/9ORijXRKRS9S5df5djd7vP7bqKZaYuLNwYE14cidmG7WQgGV3YKTgaUbcsDGmHm9JghXNv+rj7fU1we+58Q=
  - secure: tC0eQoNyz9KSbazwPLGJTih8HEx2O9svobV9lAI3ZIHBHe//8rdfecqHY/gDa9IOXERNDzj1Y0/2K8PhIrwG01kp+HYHB/XoZ+5IBdoIydY9gVgpFCpV8JYzGQrbD0pAkwRcOT5mefHi00p4vYelsYhn7biROFiiuyfLSSXUjT+XGzX6iNnqHD4xPLSKV9RM+RCakjUxdxviuhbhJzaewSGro7AS0UARt7IIeQIuOtVKCCD+MltGAGtOooE3/2KzhQuH9DGJrNsPo6Nxws+8nZ2lZNMzP8d0yvcZAwiyFnINDT7kt1YqMcURa+Z+vigGlwe/FnPoASIMZ86eSjhDN6py1TZZ6fzo1Id1KCkM4w7Rd058N6dcgkcR4R7J0/72dWMle6DzSX82jTm7MHJnUmNeLtk50Hm7ai+K0oF8wnMjY/ha7g9a6e/0AfVHGn7Ufpg/6+CZV11FFOQVCX9OWbK5AqO8W1q6zblY9zvSIp/tjHQI6BpuncSNyKvZhXxKsd3nvczgXJn/GU/7hnLbuFKzrHaoOmZoeqfYtFEgqa5lwlhoHn+V+AYK5KbKtaquLx7R23wXPRhEf2k0Ck3nHmT8d/m/LZ+0hF0igy7ZEBnBnbKqc+NrbZLOfqfKcE3m2FxuaPThJJglP/MF88+AO7bxyspKUf7qLswnI5qtEgo=
